version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: andrey
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: rag_database
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U andrey -d rag_database" ]
      interval: 5s
      retries: 5
      start_period: 10s

  api:
    build: API
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./API:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    restart: always

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
